[project]
name = "internai"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "Flask",
    "flask-cors",
    "numpy",
    "pandas",
    "scikit-learn",
    "joblib",
    "sentence-transformers",
    "torch",
    "scipy"
]

[tool.uv.sources]
torch = { index = "pytorch-cpu" }

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.vercel]
entrypoint = "src.backend:app"